language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - examples/node_modules
    - examples/.next/cache

node_js:
  - '14'

install:
  - yarn --frozen-lockfile

script:
  - yarn build:lib || yarn build:lib # workaround for https://github.com/react-page/react-page/issues/1072
  - yarn run lint
  - yarn run test

after_success:
  - yarn run coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && yarn run semantic-release'
    on:
      all_branches: true # semantic release handles tht for us
